// Code generated by "stringer -type=PlayerSourceType"; DO NOT EDIT.

package teams

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PLAYER_SOURCE_TEAM_REGISTRATION-0]
	_ = x[PLAYER_SOURCE_INDIVIDUAL_REGISTRATION-1]
}

const _PlayerSourceType_name = "PLAYER_SOURCE_TEAM_REGISTRATIONPLAYER_SOURCE_INDIVIDUAL_REGISTRATION"

var _PlayerSourceType_index = [...]uint8{0, 31, 68}

func (i PlayerSourceType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PlayerSourceType_index)-1 {
		return "PlayerSourceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PlayerSourceType_name[_PlayerSourceType_index[idx]:_PlayerSourceType_index[idx+1]]
}
