// Code generated by "stringer -type=TeamSourceType"; DO NOT EDIT.

package teams

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SOURCE_TEAM_REGISTRATION-0]
	_ = x[SOURCE_ADMIN_CREATED-1]
	_ = x[SOURCE_MIXED-2]
}

const _TeamSourceType_name = "SOURCE_TEAM_REGISTRATIONSOURCE_ADMIN_CREATEDSOURCE_MIXED"

var _TeamSourceType_index = [...]uint8{0, 24, 44, 56}

func (i TeamSourceType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TeamSourceType_index)-1 {
		return "TeamSourceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TeamSourceType_name[_TeamSourceType_index[idx]:_TeamSourceType_index[idx+1]]
}
