// Code generated by "stringer -type=GameStatus"; DO NOT EDIT.

package games

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STATUS_SCHEDULED-0]
	_ = x[STATUS_IN_PROGRESS-1]
	_ = x[STATUS_COMPLETED-2]
}

const _GameStatus_name = "STATUS_SCHEDULEDSTATUS_IN_PROGRESSSTATUS_COMPLETED"

var _GameStatus_index = [...]uint8{0, 16, 34, 50}

func (i GameStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_GameStatus_index)-1 {
		return "GameStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GameStatus_name[_GameStatus_index[idx]:_GameStatus_index[idx+1]]
}
