services:
  dynamodb:
    image: "amazon/dynamodb-local"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    ports:
      - "8000:8000"
    networks:
      - icaa-event-registration
  dynamo-create-table:
    depends_on:
      - dynamodb
    image: "amazon/aws-cli"
    networks:
      - icaa-event-registration
    environment:
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    command: >-
      dynamodb create-table
        --endpoint-url http://dynamodb:8000
        --region us-east-1
        --table-name event-registration
        --billing-mode PAY_PER_REQUEST
        --attribute-definitions
          AttributeName=PK,AttributeType=S
          AttributeName=SK,AttributeType=S
          AttributeName=GSI1PK,AttributeType=S
          AttributeName=GSI1SK,AttributeType=S
        --key-schema
          AttributeName=PK,KeyType=HASH
          AttributeName=SK,KeyType=RANGE
        --global-secondary-indexes
          '[
            {
              "IndexName": "GSI1",
              "KeySchema": [
                {"AttributeName": "GSI1PK", "KeyType": "HASH"},
                {"AttributeName": "GSI1SK", "KeyType": "RANGE"}
              ],
              "Projection": {
                "ProjectionType": "ALL"
              }
            }
          ]'

networks:
  icaa-event-registration:
    name: icaa-event-registration
