version = 0.1

[default.deploy.parameters]
stack_name = "event-registration"
resolve_s3 = true
s3_prefix = "event-registration"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["ICAAEventRegistration=197461532156.dkr.ecr.us-east-1.amazonaws.com/eventregistrationcae08890/icaaeventregistration459a6a40repo"]
