AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ICAA Event Registration API

Mappings:
  attributes:
    dynamo:
      tableName: event-registration

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    Environment:
      Variables:
        DYNAMO_TABLE_NAME: !FindInMap [attributes, dynamo, tableName]

Resources:
  ICAAEventRegistration:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - arm64
      MemorySize: 256
      Events:
        APIEvent:
          Type: HttpApi
    Metadata:
      DockerTag: v1
      DockerContext: .
      Dockerfile: Dockerfile

Outputs:
  ICAAEventRegistrationApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
