// Code generated by "stringer -type=ExperienceLevel"; DO NOT EDIT.

package registration

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NOVICE-0]
	_ = x[INTERMEDIATE-1]
	_ = x[ADVANCED-2]
}

const _ExperienceLevel_name = "NOVICEINTERMEDIATEADVANCED"

var _ExperienceLevel_index = [...]uint8{0, 6, 18, 26}

func (i ExperienceLevel) String() string {
	if i < 0 || i >= ExperienceLevel(len(_ExperienceLevel_index)-1) {
		return "ExperienceLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExperienceLevel_name[_ExperienceLevel_index[i]:_ExperienceLevel_index[i+1]]
}
