// Code generated by "stringer -type=RegistrationType"; DO NOT EDIT.

package events

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BY_INDIVIDUAL-0]
	_ = x[BY_TEAM-1]
}

const _RegistrationType_name = "BY_INDIVIDUALBY_TEAM"

var _RegistrationType_index = [...]uint8{0, 13, 20}

func (i RegistrationType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RegistrationType_index)-1 {
		return "RegistrationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RegistrationType_name[_RegistrationType_index[idx]:_RegistrationType_index[idx+1]]
}
