//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorCode.
const (
	AlreadyExists        ErrorCode = "AlreadyExists"
	AuthError            ErrorCode = "AuthError"
	EmptyBody            ErrorCode = "EmptyBody"
	InputValidationError ErrorCode = "InputValidationError"
	InternalError        ErrorCode = "InternalError"
	InvalidBody          ErrorCode = "InvalidBody"
	InvalidCursor        ErrorCode = "InvalidCursor"
	LimitOutOfBounds     ErrorCode = "LimitOutOfBounds"
	NotFound             ErrorCode = "NotFound"
	RegistrationClosed   ErrorCode = "RegistrationClosed"
)

// Defines values for ExperienceLevel.
const (
	Advanced     ExperienceLevel = "Advanced"
	Intermediate ExperienceLevel = "Intermediate"
	Novice       ExperienceLevel = "Novice"
)

// Defines values for RegistrationType.
const (
	ByIndividual RegistrationType = "ByIndividual"
	ByTeam       RegistrationType = "ByTeam"
)

// Address defines model for Address.
type Address struct {
	// City City or town
	City string `json:"city"`

	// Country Country
	Country string `json:"country"`

	// PostalCode Postal code
	PostalCode string `json:"postalCode"`

	// State State or province
	State string `json:"state"`

	// Street Street address
	Street string `json:"street"`
}

// Error defines model for Error.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// Event defines model for Event.
type Event struct {
	AllowedTeamSizeRange  Range               `json:"allowedTeamSizeRange"`
	EndTime               time.Time           `json:"endTime"`
	Id                    *openapi_types.UUID `json:"id,omitempty"`
	Location              Location            `json:"location"`
	Name                  string              `json:"name"`
	RegistrationCloseTime time.Time           `json:"registrationCloseTime"`
	RegistrationTypes     []RegistrationType  `json:"registrationTypes"`
	RulesDocLink          *string             `json:"rulesDocLink,omitempty"`
	SignUpStats           *SignUpStats        `json:"signUpStats,omitempty"`
	StartTime             time.Time           `json:"startTime"`
	Version               *int                `json:"version,omitempty"`
}

// ExperienceLevel defines model for ExperienceLevel.
type ExperienceLevel string

// IndividualRegistration defines model for IndividualRegistration.
type IndividualRegistration struct {
	Email            openapi_types.Email `json:"email"`
	EventId          *openapi_types.UUID `json:"eventId,omitempty"`
	Experience       ExperienceLevel     `json:"experience"`
	HomeCity         string              `json:"homeCity"`
	Id               *openapi_types.UUID `json:"id,omitempty"`
	Paid             *bool               `json:"paid,omitempty"`
	PlayerInfo       PlayerInfo          `json:"playerInfo"`
	RegisteredAt     *time.Time          `json:"registeredAt,omitempty"`
	RegistrationType RegistrationType    `json:"registrationType"`
	Version          *int                `json:"version,omitempty"`
}

// Location defines model for Location.
type Location struct {
	Address Address `json:"address"`
	Name    string  `json:"name"`
}

// PlayerInfo defines model for PlayerInfo.
type PlayerInfo struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

// Range defines model for Range.
type Range struct {
	Max int `json:"max"`
	Min int `json:"min"`
}

// Registration defines model for Registration.
type Registration struct {
	union json.RawMessage
}

// RegistrationType defines model for RegistrationType.
type RegistrationType string

// SignUpStats defines model for SignUpStats.
type SignUpStats struct {
	NumRosteredPlayers int `json:"numRosteredPlayers"`
	NumTeams           int `json:"numTeams"`
	NumTotalPlayers    int `json:"numTotalPlayers"`
}

// TeamRegistration defines model for TeamRegistration.
type TeamRegistration struct {
	CaptainEmail     openapi_types.Email `json:"captainEmail"`
	EventId          *openapi_types.UUID `json:"eventId,omitempty"`
	HomeCity         string              `json:"homeCity"`
	Id               *openapi_types.UUID `json:"id,omitempty"`
	Paid             *bool               `json:"paid,omitempty"`
	Players          []PlayerInfo        `json:"players"`
	RegisteredAt     *time.Time          `json:"registeredAt,omitempty"`
	RegistrationType RegistrationType    `json:"registrationType"`
	TeamName         string              `json:"teamName"`
	Version          *int                `json:"version,omitempty"`
}

// GetV1EventsParams defines parameters for GetV1Events.
type GetV1EventsParams struct {
	// Cursor Cursor of where to start from
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Max amount of events to fetch
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetV1EventsEventIdRegistrationsParams defines parameters for GetV1EventsEventIdRegistrations.
type GetV1EventsEventIdRegistrationsParams struct {
	// Cursor Cursor of where to start from
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Max amount of registrations to fetch
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostV1EventsJSONRequestBody defines body for PostV1Events for application/json ContentType.
type PostV1EventsJSONRequestBody = Event

// PostV1EventsEventIdRegisterJSONRequestBody defines body for PostV1EventsEventIdRegister for application/json ContentType.
type PostV1EventsEventIdRegisterJSONRequestBody = Registration

// AsIndividualRegistration returns the union data inside the Registration as a IndividualRegistration
func (t Registration) AsIndividualRegistration() (IndividualRegistration, error) {
	var body IndividualRegistration
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromIndividualRegistration overwrites any union data inside the Registration as the provided IndividualRegistration
func (t *Registration) FromIndividualRegistration(v IndividualRegistration) error {
	v.RegistrationType = "ByIndividual"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeIndividualRegistration performs a merge with any union data inside the Registration, using the provided IndividualRegistration
func (t *Registration) MergeIndividualRegistration(v IndividualRegistration) error {
	v.RegistrationType = "ByIndividual"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTeamRegistration returns the union data inside the Registration as a TeamRegistration
func (t Registration) AsTeamRegistration() (TeamRegistration, error) {
	var body TeamRegistration
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTeamRegistration overwrites any union data inside the Registration as the provided TeamRegistration
func (t *Registration) FromTeamRegistration(v TeamRegistration) error {
	v.RegistrationType = "ByTeam"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTeamRegistration performs a merge with any union data inside the Registration, using the provided TeamRegistration
func (t *Registration) MergeTeamRegistration(v TeamRegistration) error {
	v.RegistrationType = "ByTeam"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Registration) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"registrationType"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Registration) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "ByIndividual":
		return t.AsIndividualRegistration()
	case "ByTeam":
		return t.AsTeamRegistration()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Registration) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Registration) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all events
	// (GET /v1/events)
	GetV1Events(w http.ResponseWriter, r *http.Request, params GetV1EventsParams)
	// Create a new event
	// (POST /v1/events)
	PostV1Events(w http.ResponseWriter, r *http.Request)
	// Sign up for an event
	// (POST /v1/events/{eventId}/register)
	PostV1EventsEventIdRegister(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID)
	// Get all registrations for an event
	// (GET /v1/events/{eventId}/registrations)
	GetV1EventsEventIdRegistrations(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID, params GetV1EventsEventIdRegistrationsParams)
	// Get an event
	// (GET /v1/events/{id})
	GetV1EventsId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetV1Events operation middleware
func (siw *ServerInterfaceWrapper) GetV1Events(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetV1EventsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1Events(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostV1Events operation middleware
func (siw *ServerInterfaceWrapper) PostV1Events(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostV1Events(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostV1EventsEventIdRegister operation middleware
func (siw *ServerInterfaceWrapper) PostV1EventsEventIdRegister(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventId" -------------
	var eventId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostV1EventsEventIdRegister(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetV1EventsEventIdRegistrations operation middleware
func (siw *ServerInterfaceWrapper) GetV1EventsEventIdRegistrations(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventId" -------------
	var eventId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetV1EventsEventIdRegistrationsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1EventsEventIdRegistrations(w, r, eventId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetV1EventsId operation middleware
func (siw *ServerInterfaceWrapper) GetV1EventsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1EventsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/v1/events", wrapper.GetV1Events)
	m.HandleFunc("POST "+options.BaseURL+"/v1/events", wrapper.PostV1Events)
	m.HandleFunc("POST "+options.BaseURL+"/v1/events/{eventId}/register", wrapper.PostV1EventsEventIdRegister)
	m.HandleFunc("GET "+options.BaseURL+"/v1/events/{eventId}/registrations", wrapper.GetV1EventsEventIdRegistrations)
	m.HandleFunc("GET "+options.BaseURL+"/v1/events/{id}", wrapper.GetV1EventsId)

	return m
}

type GetV1EventsRequestObject struct {
	Params GetV1EventsParams
}

type GetV1EventsResponseObject interface {
	VisitGetV1EventsResponse(w http.ResponseWriter) error
}

type GetV1Events200JSONResponse struct {
	Cursor      *string `json:"cursor,omitempty"`
	Data        []Event `json:"data"`
	HasNextPage bool    `json:"hasNextPage"`
}

func (response GetV1Events200JSONResponse) VisitGetV1EventsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetV1Events400JSONResponse Error

func (response GetV1Events400JSONResponse) VisitGetV1EventsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetV1Events500JSONResponse Error

func (response GetV1Events500JSONResponse) VisitGetV1EventsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostV1EventsRequestObject struct {
	Body *PostV1EventsJSONRequestBody
}

type PostV1EventsResponseObject interface {
	VisitPostV1EventsResponse(w http.ResponseWriter) error
}

type PostV1Events200JSONResponse Event

func (response PostV1Events200JSONResponse) VisitPostV1EventsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostV1Events400JSONResponse Error

func (response PostV1Events400JSONResponse) VisitPostV1EventsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostV1Events500JSONResponse Error

func (response PostV1Events500JSONResponse) VisitPostV1EventsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostV1EventsEventIdRegisterRequestObject struct {
	EventId openapi_types.UUID `json:"eventId"`
	Body    *PostV1EventsEventIdRegisterJSONRequestBody
}

type PostV1EventsEventIdRegisterResponseObject interface {
	VisitPostV1EventsEventIdRegisterResponse(w http.ResponseWriter) error
}

type PostV1EventsEventIdRegister200JSONResponse struct {
	Registration Registration `json:"registration"`
}

func (response PostV1EventsEventIdRegister200JSONResponse) VisitPostV1EventsEventIdRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostV1EventsEventIdRegister400JSONResponse Error

func (response PostV1EventsEventIdRegister400JSONResponse) VisitPostV1EventsEventIdRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostV1EventsEventIdRegister403JSONResponse Error

func (response PostV1EventsEventIdRegister403JSONResponse) VisitPostV1EventsEventIdRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PostV1EventsEventIdRegister404JSONResponse Error

func (response PostV1EventsEventIdRegister404JSONResponse) VisitPostV1EventsEventIdRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostV1EventsEventIdRegister409JSONResponse Error

func (response PostV1EventsEventIdRegister409JSONResponse) VisitPostV1EventsEventIdRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostV1EventsEventIdRegister500JSONResponse Error

func (response PostV1EventsEventIdRegister500JSONResponse) VisitPostV1EventsEventIdRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetV1EventsEventIdRegistrationsRequestObject struct {
	EventId openapi_types.UUID `json:"eventId"`
	Params  GetV1EventsEventIdRegistrationsParams
}

type GetV1EventsEventIdRegistrationsResponseObject interface {
	VisitGetV1EventsEventIdRegistrationsResponse(w http.ResponseWriter) error
}

type GetV1EventsEventIdRegistrations200JSONResponse struct {
	Cursor      *string        `json:"cursor,omitempty"`
	Data        []Registration `json:"data"`
	HasNextPage bool           `json:"hasNextPage"`
}

func (response GetV1EventsEventIdRegistrations200JSONResponse) VisitGetV1EventsEventIdRegistrationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetV1EventsEventIdRegistrations400JSONResponse Error

func (response GetV1EventsEventIdRegistrations400JSONResponse) VisitGetV1EventsEventIdRegistrationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetV1EventsEventIdRegistrations500JSONResponse Error

func (response GetV1EventsEventIdRegistrations500JSONResponse) VisitGetV1EventsEventIdRegistrationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetV1EventsIdRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetV1EventsIdResponseObject interface {
	VisitGetV1EventsIdResponse(w http.ResponseWriter) error
}

type GetV1EventsId200JSONResponse struct {
	Event Event `json:"event"`
}

func (response GetV1EventsId200JSONResponse) VisitGetV1EventsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetV1EventsId400JSONResponse Error

func (response GetV1EventsId400JSONResponse) VisitGetV1EventsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetV1EventsId404JSONResponse Error

func (response GetV1EventsId404JSONResponse) VisitGetV1EventsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetV1EventsId500JSONResponse Error

func (response GetV1EventsId500JSONResponse) VisitGetV1EventsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get all events
	// (GET /v1/events)
	GetV1Events(ctx context.Context, request GetV1EventsRequestObject) (GetV1EventsResponseObject, error)
	// Create a new event
	// (POST /v1/events)
	PostV1Events(ctx context.Context, request PostV1EventsRequestObject) (PostV1EventsResponseObject, error)
	// Sign up for an event
	// (POST /v1/events/{eventId}/register)
	PostV1EventsEventIdRegister(ctx context.Context, request PostV1EventsEventIdRegisterRequestObject) (PostV1EventsEventIdRegisterResponseObject, error)
	// Get all registrations for an event
	// (GET /v1/events/{eventId}/registrations)
	GetV1EventsEventIdRegistrations(ctx context.Context, request GetV1EventsEventIdRegistrationsRequestObject) (GetV1EventsEventIdRegistrationsResponseObject, error)
	// Get an event
	// (GET /v1/events/{id})
	GetV1EventsId(ctx context.Context, request GetV1EventsIdRequestObject) (GetV1EventsIdResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetV1Events operation middleware
func (sh *strictHandler) GetV1Events(w http.ResponseWriter, r *http.Request, params GetV1EventsParams) {
	var request GetV1EventsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetV1Events(ctx, request.(GetV1EventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetV1Events")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetV1EventsResponseObject); ok {
		if err := validResponse.VisitGetV1EventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostV1Events operation middleware
func (sh *strictHandler) PostV1Events(w http.ResponseWriter, r *http.Request) {
	var request PostV1EventsRequestObject

	var body PostV1EventsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostV1Events(ctx, request.(PostV1EventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostV1Events")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostV1EventsResponseObject); ok {
		if err := validResponse.VisitPostV1EventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostV1EventsEventIdRegister operation middleware
func (sh *strictHandler) PostV1EventsEventIdRegister(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID) {
	var request PostV1EventsEventIdRegisterRequestObject

	request.EventId = eventId

	var body PostV1EventsEventIdRegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostV1EventsEventIdRegister(ctx, request.(PostV1EventsEventIdRegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostV1EventsEventIdRegister")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostV1EventsEventIdRegisterResponseObject); ok {
		if err := validResponse.VisitPostV1EventsEventIdRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetV1EventsEventIdRegistrations operation middleware
func (sh *strictHandler) GetV1EventsEventIdRegistrations(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID, params GetV1EventsEventIdRegistrationsParams) {
	var request GetV1EventsEventIdRegistrationsRequestObject

	request.EventId = eventId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetV1EventsEventIdRegistrations(ctx, request.(GetV1EventsEventIdRegistrationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetV1EventsEventIdRegistrations")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetV1EventsEventIdRegistrationsResponseObject); ok {
		if err := validResponse.VisitGetV1EventsEventIdRegistrationsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetV1EventsId operation middleware
func (sh *strictHandler) GetV1EventsId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetV1EventsIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetV1EventsId(ctx, request.(GetV1EventsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetV1EventsId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetV1EventsIdResponseObject); ok {
		if err := validResponse.VisitGetV1EventsIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabW/bOBL+KwTvPqq2bMd3jYAFznHTrhdpGiRpDpciHxhxbLMrkVqScuIt/N8PJCVb",
	"lOSXtE1f7jZYbG2J5Lw988wMk084FmkmOHCtcPQJq3gOKbEfR5RKUPZjJkUGUjOw32Kml+ZfCiqWLNNM",
	"cBzhMdNLJCTS4oHjAMMjSbMEcIRHfFk8S8njGfCZnuNoGAY4Zbz8OgiwXmZmtdKS8RleBTgWOdeyTVLx",
	"oirk/dVop4B+i4BMKE2SsaDQlHFh36HYvKzKOQ77vdCX1N9vitJEtwi5Mo+NzzIpFozHvqjx0y1SWgLo",
	"NkHmOSJFRKtSev0BeksYR1e6ZtZwuMeuVYAl/JEzCRRHH0rhgcNHabTn5k1Q79anifuPEGuj/amUQrbA",
	"rQjQ3yVMcYT/1t0gtlvAtWu3WhGrAKegFJnZPVUUopzDYwaxBorArEcijnMpgXbwPtsKHJQnb9W+BBPw",
	"PDX7JlyD5CRxpgX4jKVMv8v1u+mJyDk1oZjwBUkYHedS2SXnQr8273CAT9NML08EXW6WFd9GiQRCl6eP",
	"TGlzyCXMmNKSmHiPE6GA2i1Zrm/MLvu81GGU67n7fNcCodMFcN0MAkkS8QD0Gkh6xf6ES8Jne4PiFq0C",
	"DJxes7QWkH7YH74IX77oHV/3+1EYRmHYCcPwFgd4KmRKNI4wJRpeaLO1RVNG/QPD4udFy//Kn+rhec6M",
	"l4wj3/FkiSMtc2iRk4iYuDzabe5ZuW4VYE7q5k7GoxEa5xkydj8104yWtQDvcOg/r/uDaHgcDY+f5tCq",
	"jOtl5gLPNKRqb6RrO20WMj5xe3trWURKsrSi8gTUKxGfMf67b8Vc60xF3S4VserMhJgl0IlFar7nKXDd",
	"pV1C1XRKpsr8R6e0u2DwUKfKsI0d2Yy/zwzp7jXoqrLU8bfUOyHcexkd/SMaDjq9l8PDPb4AqQpkrU/t",
	"bYUk4xpmIBvkZGFcHlVgrwLbqvqbXNwGqTYYBO3p73u0lRMfM5AMeAxnsICkyoznYsFswbMUmQJlrlqM",
	"6ILwGKg5r5I9/qKGIyecsgWjOUmqUGzSGKSEJX4QPxIOHSrgX8Ujg7ZqAN0WD169cH/JB8Ojk29EUbD2",
	"895CWYvIKsBzkcK4aOkaXVuAGp3VIdZ/K27OSE2SW7dl370QCRBL0FlCliAnfCr2eexis3LNkSCBjvSX",
	"kcFe2+p5+Dkk/HUIpqFJUOecEu01BwXr7FmDzHO9h9wimm08clYpwbW+ZDOk7PJNOcu0luYC6mgs0jTn",
	"ZowZg+Gbp8K+5rWCh0sN2+y68FDoWzZlUunzhrK/EQ4754JeWwtD2o56JZ56Us3CjYoVEW12rttF38SU",
	"PHoauTaIpaZC9JqotG/rUF5vCPfC2Oy29rbrWCsclJkJKmWcaDeVpCTLjBeiT/hkuSk42yC3pSQF+GRp",
	"yui2beadt8GQlfPa0oWwmY6rAAsO76Y4+rA7DbbotAp2b2vqdFdzWMlPZXX3HLQ22SvptSUNzF753ZqP",
	"HJ6nl8LRjMsh5QMp3A2MwBxgVPK39Q7aJjRJWoUOD0Cjz7seXZQaBW3WNUW3YbgRqOYwTTJNGD9t9kHF",
	"m5+5Dfo/7mQOn9X8fmb3lPZzNTsaSNqsctdzQK/ZbK4Zn6G3gs+EUHameSIQvnsrtTbP66a8hN6gYWsz",
	"ZRRiRcPhXxKOOBpdTNBUSJQSTmbGX1YZhQinyMx65lGe2SXujb05Y3pzw2Gvj1Ct4q1dh3udsBPaepUB",
	"JxnDER7YR0ZfPbfg7S56XXe6+TZru8+8BC0ZLEAhghKmNBJTRJKkUArb4510Qz34Deib3mn5LiOSpKBt",
	"znxo3C3bazhz3sMcJCAtkJ2e0VRaPjQNCP4jB3v97FpJHJdXdw6cPvz+0z/Obwe/zemvb9Xk12RBr07S",
	"+8FNfjs+Ccmb97Pbf7/+k765WU7e3PDbh19+abuKrCv5ljwikoqcW8OLGGmBpqDj+RYlE5Yy7elIYUry",
	"RLuy59dA8uiqmFdHWzqy1Z1BqcoEV6689MPQXdlyXVwjkixLmOveux+Vy5+NDrXi5Bz5lf0XGCYiB/Oj",
	"uwBdNdlwTtQ5POqL+tVyOzHX8t6q4J/Rnpu1nFzDu8y3VYCPnujkvRfnbZJPCEXGAFDaCh1+C6Hv+e/c",
	"TGIK5AKku6XvWF+qPE2JXLpkruZ68XucFjqjKeMIOM0E49qkRyyBaEAEcXhw2xtMcSFUlSoKB9hL969m",
	"vMNX03hHnVqgeyhUpbgKIoOz1Rfm22cpZipooZBz218oxOMmlsyCTe3qfioK+apb1nFLeK1YNbNOWVgJ",
	"PwCbp+7sy/LkPVVt8spQiJ7D+mhbIkzJ3VSIauNRxVx7XfvMPrhe2+6eJ8n8abUZ4ur7Z045v8TJ2nT2",
	"BCO2N5IHlZJqFlc3f5dkdjIHzy/zXNhqIR6AmjiXqVgYffT8CjhWZwpxodFU5NzTAz0wPXe6HD+/Llci",
	"BcHBaEPcL5BtVw/UcE/OKUik50whN+v/SHTbSpB7CNfBe/sQUTYS3urdFFwZJDwGLkX9tDQcPPsc1OsP",
	"joZPH2784PyPzjjDo0G/98WDS/3W+MeaX7xA/tVAHsI+dX5jdLWTzAy127Xofolsmm9lL8svX85V7Ht0",
	"i18tFaH8U6dDpiI/HdzWQ9suKK8Uvgvkv2Gbs+5xfsBc22SVeWdXt+H+Qgqax3YucItwgHOZVP4yiWSs",
	"w2JCOg9CJrSLmyXsTMQkQRQWbUdE3W5i3s+F0tEgDMMuXt2t/hsAAP//uaM87IgrAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
