//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	IcaaBearerAuthScopes = "icaaBearerAuth.Scopes"
	IcaaCookieAuthScopes = "icaaCookieAuth.Scopes"
)

// Defines values for ErrorCode.
const (
	AlreadyExists        ErrorCode = "AlreadyExists"
	AuthError            ErrorCode = "AuthError"
	CaptchaInvalid       ErrorCode = "CaptchaInvalid"
	EmptyBody            ErrorCode = "EmptyBody"
	InputValidationError ErrorCode = "InputValidationError"
	InternalError        ErrorCode = "InternalError"
	InvalidBody          ErrorCode = "InvalidBody"
	InvalidCursor        ErrorCode = "InvalidCursor"
	LimitOutOfBounds     ErrorCode = "LimitOutOfBounds"
	NotFound             ErrorCode = "NotFound"
	RegistrationClosed   ErrorCode = "RegistrationClosed"
	RegistrationUnpaid   ErrorCode = "RegistrationUnpaid"
)

// Defines values for ExperienceLevel.
const (
	Advanced     ExperienceLevel = "Advanced"
	Intermediate ExperienceLevel = "Intermediate"
	Novice       ExperienceLevel = "Novice"
)

// Defines values for RegistrationType.
const (
	ByIndividual RegistrationType = "ByIndividual"
	ByTeam       RegistrationType = "ByTeam"
)

// Address defines model for Address.
type Address struct {
	// City City or town
	City string `json:"city"`

	// Country Country
	Country string `json:"country"`

	// PostalCode Postal code
	PostalCode string `json:"postalCode"`

	// State State or province
	State string `json:"state"`

	// Street Street address
	Street string `json:"street"`
}

// Error defines model for Error.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// Event defines model for Event.
type Event struct {
	AllowedTeamSizeRange Range               `json:"allowedTeamSizeRange"`
	EndTime              time.Time           `json:"endTime"`
	Id                   *openapi_types.UUID `json:"id,omitempty"`

	// ImageName A file name that exists in the UI assets to use as the logo.
	ImageName             *string                   `json:"imageName,omitempty"`
	Location              Location                  `json:"location"`
	Name                  string                    `json:"name"`
	RegistrationCloseTime time.Time                 `json:"registrationCloseTime"`
	RegistrationOptions   []EventRegistrationOption `json:"registrationOptions"`
	RulesDocLink          *string                   `json:"rulesDocLink,omitempty"`
	SignUpStats           *SignUpStats              `json:"signUpStats,omitempty"`
	StartTime             time.Time                 `json:"startTime"`

	// TimeZone Time zone of the event. Defaults to UTC if not set.
	TimeZone *string `json:"timeZone,omitempty"`
	Version  *int    `json:"version,omitempty"`
}

// EventRegistrationOption defines model for EventRegistrationOption.
type EventRegistrationOption struct {
	Price            Money            `json:"price"`
	RegistrationType RegistrationType `json:"registrationType"`
}

// ExperienceLevel defines model for ExperienceLevel.
type ExperienceLevel string

// IndividualRegistration defines model for IndividualRegistration.
type IndividualRegistration struct {
	Email            openapi_types.Email `json:"email"`
	EventId          *openapi_types.UUID `json:"eventId,omitempty"`
	Experience       ExperienceLevel     `json:"experience"`
	HomeCity         string              `json:"homeCity"`
	Id               *openapi_types.UUID `json:"id,omitempty"`
	Paid             *bool               `json:"paid,omitempty"`
	PlayerInfo       PlayerInfo          `json:"playerInfo"`
	RegisteredAt     *time.Time          `json:"registeredAt,omitempty"`
	RegistrationType RegistrationType    `json:"registrationType"`
	Version          *int                `json:"version,omitempty"`
}

// Location defines model for Location.
type Location struct {
	Address Address `json:"address"`
	Name    string  `json:"name"`
}

// Money defines model for Money.
type Money struct {
	// Amount Minor units of money (i.e. 100 == $1 in USD)
	Amount   int    `json:"amount"`
	Currency string `json:"currency"`
}

// PlayerInfo defines model for PlayerInfo.
type PlayerInfo struct {
	// Email Optional email for each player
	Email     *openapi_types.Email `json:"email,omitempty"`
	FirstName string               `json:"firstName"`
	LastName  string               `json:"lastName"`
}

// Range defines model for Range.
type Range struct {
	Max int `json:"max"`
	Min int `json:"min"`
}

// Registration defines model for Registration.
type Registration struct {
	union json.RawMessage
}

// RegistrationPaymentInfo defines model for RegistrationPaymentInfo.
type RegistrationPaymentInfo struct {
	ClientSecret string       `json:"clientSecret"`
	ExpiresAt    time.Time    `json:"expiresAt"`
	Registration Registration `json:"registration"`
}

// RegistrationType defines model for RegistrationType.
type RegistrationType string

// SignUpStats defines model for SignUpStats.
type SignUpStats struct {
	NumRosteredPlayers int `json:"numRosteredPlayers"`
	NumTeams           int `json:"numTeams"`
	NumTotalPlayers    int `json:"numTotalPlayers"`
}

// TeamRegistration defines model for TeamRegistration.
type TeamRegistration struct {
	CaptainEmail     openapi_types.Email `json:"captainEmail"`
	EventId          *openapi_types.UUID `json:"eventId,omitempty"`
	HomeCity         string              `json:"homeCity"`
	Id               *openapi_types.UUID `json:"id,omitempty"`
	Paid             *bool               `json:"paid,omitempty"`
	Players          []PlayerInfo        `json:"players"`
	RegisteredAt     *time.Time          `json:"registeredAt,omitempty"`
	RegistrationType RegistrationType    `json:"registrationType"`
	TeamName         string              `json:"teamName"`
	Version          *int                `json:"version,omitempty"`
}

// GetEventsV1Params defines parameters for GetEventsV1.
type GetEventsV1Params struct {
	// Cursor Cursor of where to start from
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Max amount of events to fetch
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostEventsV1AdminTestEmailJSONBody defines parameters for PostEventsV1AdminTestEmail.
type PostEventsV1AdminTestEmailJSONBody struct {
	Email openapi_types.Email `json:"email"`
}

// PostEventsV1AdminTestMailerliteJSONBody defines parameters for PostEventsV1AdminTestMailerlite.
type PostEventsV1AdminTestMailerliteJSONBody struct {
	Emails []openapi_types.Email `json:"emails"`

	// GroupName Name for the test group. Defaults to "MailerLite Test Group".
	GroupName        *string          `json:"groupName,omitempty"`
	RegistrationType RegistrationType `json:"registrationType"`

	// TeamName Team name required when registrationType is ByTeam.
	TeamName *string `json:"teamName,omitempty"`
}

// PostEventsV1EventIdRegisterParams defines parameters for PostEventsV1EventIdRegister.
type PostEventsV1EventIdRegisterParams struct {
	// CfTurnstileResponse Cloudflare turnstile CAPTCHA
	CfTurnstileResponse string `json:"cf-turnstile-response"`
}

// GetEventsV1EventIdRegistrationsParams defines parameters for GetEventsV1EventIdRegistrations.
type GetEventsV1EventIdRegistrationsParams struct {
	// Cursor Cursor of where to start from
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Max amount of registrations to fetch
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostEventsV1EventIdRegistrationsParams defines parameters for PostEventsV1EventIdRegistrations.
type PostEventsV1EventIdRegistrationsParams struct {
	// CfTurnstileResponse Cloudflare turnstile CAPTCHA
	CfTurnstileResponse string `json:"cf-turnstile-response"`
}

// PostEventsV1JSONRequestBody defines body for PostEventsV1 for application/json ContentType.
type PostEventsV1JSONRequestBody = Event

// PostEventsV1AdminTestEmailJSONRequestBody defines body for PostEventsV1AdminTestEmail for application/json ContentType.
type PostEventsV1AdminTestEmailJSONRequestBody PostEventsV1AdminTestEmailJSONBody

// PostEventsV1AdminTestMailerliteJSONRequestBody defines body for PostEventsV1AdminTestMailerlite for application/json ContentType.
type PostEventsV1AdminTestMailerliteJSONRequestBody PostEventsV1AdminTestMailerliteJSONBody

// PostEventsV1EventIdRegisterJSONRequestBody defines body for PostEventsV1EventIdRegister for application/json ContentType.
type PostEventsV1EventIdRegisterJSONRequestBody = Registration

// PostEventsV1EventIdRegistrationsJSONRequestBody defines body for PostEventsV1EventIdRegistrations for application/json ContentType.
type PostEventsV1EventIdRegistrationsJSONRequestBody = Registration

// PatchEventsV1IdJSONRequestBody defines body for PatchEventsV1Id for application/json ContentType.
type PatchEventsV1IdJSONRequestBody = Event

// AsIndividualRegistration returns the union data inside the Registration as a IndividualRegistration
func (t Registration) AsIndividualRegistration() (IndividualRegistration, error) {
	var body IndividualRegistration
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromIndividualRegistration overwrites any union data inside the Registration as the provided IndividualRegistration
func (t *Registration) FromIndividualRegistration(v IndividualRegistration) error {
	v.RegistrationType = "ByIndividual"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeIndividualRegistration performs a merge with any union data inside the Registration, using the provided IndividualRegistration
func (t *Registration) MergeIndividualRegistration(v IndividualRegistration) error {
	v.RegistrationType = "ByIndividual"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTeamRegistration returns the union data inside the Registration as a TeamRegistration
func (t Registration) AsTeamRegistration() (TeamRegistration, error) {
	var body TeamRegistration
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTeamRegistration overwrites any union data inside the Registration as the provided TeamRegistration
func (t *Registration) FromTeamRegistration(v TeamRegistration) error {
	v.RegistrationType = "ByTeam"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTeamRegistration performs a merge with any union data inside the Registration, using the provided TeamRegistration
func (t *Registration) MergeTeamRegistration(v TeamRegistration) error {
	v.RegistrationType = "ByTeam"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Registration) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"registrationType"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Registration) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "ByIndividual":
		return t.AsIndividualRegistration()
	case "ByTeam":
		return t.AsTeamRegistration()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Registration) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Registration) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all events
	// (GET /events/v1)
	GetEventsV1(w http.ResponseWriter, r *http.Request, params GetEventsV1Params)
	// Create a new event
	// (POST /events/v1)
	PostEventsV1(w http.ResponseWriter, r *http.Request)
	// Manually confirm a registration as paid
	// (POST /events/v1/admin/registrations/{eventId}/{email}/confirm)
	PostEventsV1AdminRegistrationsEventIdEmailConfirm(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID, email openapi_types.Email)
	// Resend registration notifications
	// (POST /events/v1/admin/registrations/{eventId}/{email}/notify)
	PostEventsV1AdminRegistrationsEventIdEmailNotify(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID, email openapi_types.Email)
	// Test email sending
	// (POST /events/v1/admin/test-email)
	PostEventsV1AdminTestEmail(w http.ResponseWriter, r *http.Request)
	// Test MailerLite integration
	// (POST /events/v1/admin/test-mailerlite)
	PostEventsV1AdminTestMailerlite(w http.ResponseWriter, r *http.Request)
	// Sign up for an event
	// (POST /events/v1/{eventId}/register)
	PostEventsV1EventIdRegister(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID, params PostEventsV1EventIdRegisterParams)
	// Get all registrations for an event
	// (GET /events/v1/{eventId}/registrations)
	GetEventsV1EventIdRegistrations(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID, params GetEventsV1EventIdRegistrationsParams)
	// Sign up for an event
	// (POST /events/v1/{eventId}/registrations)
	PostEventsV1EventIdRegistrations(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID, params PostEventsV1EventIdRegistrationsParams)
	// Get an event
	// (GET /events/v1/{id})
	GetEventsV1Id(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update an event
	// (PATCH /events/v1/{id})
	PatchEventsV1Id(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetEventsV1 operation middleware
func (siw *ServerInterfaceWrapper) GetEventsV1(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsV1Params

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventsV1(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEventsV1 operation middleware
func (siw *ServerInterfaceWrapper) PostEventsV1(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, IcaaBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEventsV1(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEventsV1AdminRegistrationsEventIdEmailConfirm operation middleware
func (siw *ServerInterfaceWrapper) PostEventsV1AdminRegistrationsEventIdEmailConfirm(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventId" -------------
	var eventId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	// ------------- Path parameter "email" -------------
	var email openapi_types.Email

	err = runtime.BindStyledParameterWithOptions("simple", "email", r.PathValue("email"), &email, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "email", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, IcaaBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEventsV1AdminRegistrationsEventIdEmailConfirm(w, r, eventId, email)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEventsV1AdminRegistrationsEventIdEmailNotify operation middleware
func (siw *ServerInterfaceWrapper) PostEventsV1AdminRegistrationsEventIdEmailNotify(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventId" -------------
	var eventId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	// ------------- Path parameter "email" -------------
	var email openapi_types.Email

	err = runtime.BindStyledParameterWithOptions("simple", "email", r.PathValue("email"), &email, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "email", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, IcaaBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEventsV1AdminRegistrationsEventIdEmailNotify(w, r, eventId, email)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEventsV1AdminTestEmail operation middleware
func (siw *ServerInterfaceWrapper) PostEventsV1AdminTestEmail(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, IcaaBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEventsV1AdminTestEmail(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEventsV1AdminTestMailerlite operation middleware
func (siw *ServerInterfaceWrapper) PostEventsV1AdminTestMailerlite(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, IcaaBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEventsV1AdminTestMailerlite(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEventsV1EventIdRegister operation middleware
func (siw *ServerInterfaceWrapper) PostEventsV1EventIdRegister(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventId" -------------
	var eventId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PostEventsV1EventIdRegisterParams

	headers := r.Header

	// ------------- Required header parameter "cf-turnstile-response" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("cf-turnstile-response")]; found {
		var CfTurnstileResponse string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "cf-turnstile-response", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "cf-turnstile-response", valueList[0], &CfTurnstileResponse, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cf-turnstile-response", Err: err})
			return
		}

		params.CfTurnstileResponse = CfTurnstileResponse

	} else {
		err := fmt.Errorf("Header parameter cf-turnstile-response is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "cf-turnstile-response", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEventsV1EventIdRegister(w, r, eventId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEventsV1EventIdRegistrations operation middleware
func (siw *ServerInterfaceWrapper) GetEventsV1EventIdRegistrations(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventId" -------------
	var eventId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, IcaaBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsV1EventIdRegistrationsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventsV1EventIdRegistrations(w, r, eventId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEventsV1EventIdRegistrations operation middleware
func (siw *ServerInterfaceWrapper) PostEventsV1EventIdRegistrations(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventId" -------------
	var eventId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PostEventsV1EventIdRegistrationsParams

	headers := r.Header

	// ------------- Required header parameter "cf-turnstile-response" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("cf-turnstile-response")]; found {
		var CfTurnstileResponse string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "cf-turnstile-response", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "cf-turnstile-response", valueList[0], &CfTurnstileResponse, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cf-turnstile-response", Err: err})
			return
		}

		params.CfTurnstileResponse = CfTurnstileResponse

	} else {
		err := fmt.Errorf("Header parameter cf-turnstile-response is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "cf-turnstile-response", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEventsV1EventIdRegistrations(w, r, eventId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEventsV1Id operation middleware
func (siw *ServerInterfaceWrapper) GetEventsV1Id(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventsV1Id(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchEventsV1Id operation middleware
func (siw *ServerInterfaceWrapper) PatchEventsV1Id(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, IcaaBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchEventsV1Id(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/events/v1", wrapper.GetEventsV1)
	m.HandleFunc("POST "+options.BaseURL+"/events/v1", wrapper.PostEventsV1)
	m.HandleFunc("POST "+options.BaseURL+"/events/v1/admin/registrations/{eventId}/{email}/confirm", wrapper.PostEventsV1AdminRegistrationsEventIdEmailConfirm)
	m.HandleFunc("POST "+options.BaseURL+"/events/v1/admin/registrations/{eventId}/{email}/notify", wrapper.PostEventsV1AdminRegistrationsEventIdEmailNotify)
	m.HandleFunc("POST "+options.BaseURL+"/events/v1/admin/test-email", wrapper.PostEventsV1AdminTestEmail)
	m.HandleFunc("POST "+options.BaseURL+"/events/v1/admin/test-mailerlite", wrapper.PostEventsV1AdminTestMailerlite)
	m.HandleFunc("POST "+options.BaseURL+"/events/v1/{eventId}/register", wrapper.PostEventsV1EventIdRegister)
	m.HandleFunc("GET "+options.BaseURL+"/events/v1/{eventId}/registrations", wrapper.GetEventsV1EventIdRegistrations)
	m.HandleFunc("POST "+options.BaseURL+"/events/v1/{eventId}/registrations", wrapper.PostEventsV1EventIdRegistrations)
	m.HandleFunc("GET "+options.BaseURL+"/events/v1/{id}", wrapper.GetEventsV1Id)
	m.HandleFunc("PATCH "+options.BaseURL+"/events/v1/{id}", wrapper.PatchEventsV1Id)

	return m
}

type GetEventsV1RequestObject struct {
	Params GetEventsV1Params
}

type GetEventsV1ResponseObject interface {
	VisitGetEventsV1Response(w http.ResponseWriter) error
}

type GetEventsV1200JSONResponse struct {
	Cursor      *string `json:"cursor,omitempty"`
	Data        []Event `json:"data"`
	HasNextPage bool    `json:"hasNextPage"`
}

func (response GetEventsV1200JSONResponse) VisitGetEventsV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetEventsV1400JSONResponse Error

func (response GetEventsV1400JSONResponse) VisitGetEventsV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetEventsV1500JSONResponse Error

func (response GetEventsV1500JSONResponse) VisitGetEventsV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1RequestObject struct {
	Body *PostEventsV1JSONRequestBody
}

type PostEventsV1ResponseObject interface {
	VisitPostEventsV1Response(w http.ResponseWriter) error
}

type PostEventsV1200JSONResponse Event

func (response PostEventsV1200JSONResponse) VisitPostEventsV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1400JSONResponse Error

func (response PostEventsV1400JSONResponse) VisitPostEventsV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1500JSONResponse Error

func (response PostEventsV1500JSONResponse) VisitPostEventsV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1AdminRegistrationsEventIdEmailConfirmRequestObject struct {
	EventId openapi_types.UUID  `json:"eventId"`
	Email   openapi_types.Email `json:"email"`
}

type PostEventsV1AdminRegistrationsEventIdEmailConfirmResponseObject interface {
	VisitPostEventsV1AdminRegistrationsEventIdEmailConfirmResponse(w http.ResponseWriter) error
}

type PostEventsV1AdminRegistrationsEventIdEmailConfirm200JSONResponse struct {
	// AlreadyPaid True if the registration was already paid before this call.
	AlreadyPaid  bool         `json:"alreadyPaid"`
	Registration Registration `json:"registration"`
}

func (response PostEventsV1AdminRegistrationsEventIdEmailConfirm200JSONResponse) VisitPostEventsV1AdminRegistrationsEventIdEmailConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1AdminRegistrationsEventIdEmailConfirm400JSONResponse Error

func (response PostEventsV1AdminRegistrationsEventIdEmailConfirm400JSONResponse) VisitPostEventsV1AdminRegistrationsEventIdEmailConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1AdminRegistrationsEventIdEmailConfirm404JSONResponse Error

func (response PostEventsV1AdminRegistrationsEventIdEmailConfirm404JSONResponse) VisitPostEventsV1AdminRegistrationsEventIdEmailConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1AdminRegistrationsEventIdEmailConfirm500JSONResponse Error

func (response PostEventsV1AdminRegistrationsEventIdEmailConfirm500JSONResponse) VisitPostEventsV1AdminRegistrationsEventIdEmailConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1AdminRegistrationsEventIdEmailNotifyRequestObject struct {
	EventId openapi_types.UUID  `json:"eventId"`
	Email   openapi_types.Email `json:"email"`
}

type PostEventsV1AdminRegistrationsEventIdEmailNotifyResponseObject interface {
	VisitPostEventsV1AdminRegistrationsEventIdEmailNotifyResponse(w http.ResponseWriter) error
}

type PostEventsV1AdminRegistrationsEventIdEmailNotify200JSONResponse struct {
	Registration Registration `json:"registration"`
}

func (response PostEventsV1AdminRegistrationsEventIdEmailNotify200JSONResponse) VisitPostEventsV1AdminRegistrationsEventIdEmailNotifyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1AdminRegistrationsEventIdEmailNotify400JSONResponse Error

func (response PostEventsV1AdminRegistrationsEventIdEmailNotify400JSONResponse) VisitPostEventsV1AdminRegistrationsEventIdEmailNotifyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1AdminRegistrationsEventIdEmailNotify404JSONResponse Error

func (response PostEventsV1AdminRegistrationsEventIdEmailNotify404JSONResponse) VisitPostEventsV1AdminRegistrationsEventIdEmailNotifyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1AdminRegistrationsEventIdEmailNotify409JSONResponse Error

func (response PostEventsV1AdminRegistrationsEventIdEmailNotify409JSONResponse) VisitPostEventsV1AdminRegistrationsEventIdEmailNotifyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1AdminRegistrationsEventIdEmailNotify500JSONResponse Error

func (response PostEventsV1AdminRegistrationsEventIdEmailNotify500JSONResponse) VisitPostEventsV1AdminRegistrationsEventIdEmailNotifyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1AdminTestEmailRequestObject struct {
	Body *PostEventsV1AdminTestEmailJSONRequestBody
}

type PostEventsV1AdminTestEmailResponseObject interface {
	VisitPostEventsV1AdminTestEmailResponse(w http.ResponseWriter) error
}

type PostEventsV1AdminTestEmail200Response struct {
}

func (response PostEventsV1AdminTestEmail200Response) VisitPostEventsV1AdminTestEmailResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PostEventsV1AdminTestEmail400JSONResponse Error

func (response PostEventsV1AdminTestEmail400JSONResponse) VisitPostEventsV1AdminTestEmailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1AdminTestEmail500JSONResponse Error

func (response PostEventsV1AdminTestEmail500JSONResponse) VisitPostEventsV1AdminTestEmailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1AdminTestMailerliteRequestObject struct {
	Body *PostEventsV1AdminTestMailerliteJSONRequestBody
}

type PostEventsV1AdminTestMailerliteResponseObject interface {
	VisitPostEventsV1AdminTestMailerliteResponse(w http.ResponseWriter) error
}

type PostEventsV1AdminTestMailerlite200JSONResponse struct {
	GroupId   *string `json:"groupId,omitempty"`
	GroupName *string `json:"groupName,omitempty"`
}

func (response PostEventsV1AdminTestMailerlite200JSONResponse) VisitPostEventsV1AdminTestMailerliteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1AdminTestMailerlite400JSONResponse Error

func (response PostEventsV1AdminTestMailerlite400JSONResponse) VisitPostEventsV1AdminTestMailerliteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1AdminTestMailerlite500JSONResponse Error

func (response PostEventsV1AdminTestMailerlite500JSONResponse) VisitPostEventsV1AdminTestMailerliteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1EventIdRegisterRequestObject struct {
	EventId openapi_types.UUID `json:"eventId"`
	Params  PostEventsV1EventIdRegisterParams
	Body    *PostEventsV1EventIdRegisterJSONRequestBody
}

type PostEventsV1EventIdRegisterResponseObject interface {
	VisitPostEventsV1EventIdRegisterResponse(w http.ResponseWriter) error
}

type PostEventsV1EventIdRegister200JSONResponse struct {
	Registration Registration `json:"registration"`
}

func (response PostEventsV1EventIdRegister200JSONResponse) VisitPostEventsV1EventIdRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1EventIdRegister400JSONResponse Error

func (response PostEventsV1EventIdRegister400JSONResponse) VisitPostEventsV1EventIdRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1EventIdRegister403JSONResponse Error

func (response PostEventsV1EventIdRegister403JSONResponse) VisitPostEventsV1EventIdRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1EventIdRegister404JSONResponse Error

func (response PostEventsV1EventIdRegister404JSONResponse) VisitPostEventsV1EventIdRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1EventIdRegister409JSONResponse Error

func (response PostEventsV1EventIdRegister409JSONResponse) VisitPostEventsV1EventIdRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1EventIdRegister500JSONResponse Error

func (response PostEventsV1EventIdRegister500JSONResponse) VisitPostEventsV1EventIdRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetEventsV1EventIdRegistrationsRequestObject struct {
	EventId openapi_types.UUID `json:"eventId"`
	Params  GetEventsV1EventIdRegistrationsParams
}

type GetEventsV1EventIdRegistrationsResponseObject interface {
	VisitGetEventsV1EventIdRegistrationsResponse(w http.ResponseWriter) error
}

type GetEventsV1EventIdRegistrations200JSONResponse struct {
	Cursor      *string        `json:"cursor,omitempty"`
	Data        []Registration `json:"data"`
	HasNextPage bool           `json:"hasNextPage"`
}

func (response GetEventsV1EventIdRegistrations200JSONResponse) VisitGetEventsV1EventIdRegistrationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetEventsV1EventIdRegistrations400JSONResponse Error

func (response GetEventsV1EventIdRegistrations400JSONResponse) VisitGetEventsV1EventIdRegistrationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetEventsV1EventIdRegistrations500JSONResponse Error

func (response GetEventsV1EventIdRegistrations500JSONResponse) VisitGetEventsV1EventIdRegistrationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1EventIdRegistrationsRequestObject struct {
	EventId openapi_types.UUID `json:"eventId"`
	Params  PostEventsV1EventIdRegistrationsParams
	Body    *PostEventsV1EventIdRegistrationsJSONRequestBody
}

type PostEventsV1EventIdRegistrationsResponseObject interface {
	VisitPostEventsV1EventIdRegistrationsResponse(w http.ResponseWriter) error
}

type PostEventsV1EventIdRegistrations200JSONResponse struct {
	Info RegistrationPaymentInfo `json:"info"`
}

func (response PostEventsV1EventIdRegistrations200JSONResponse) VisitPostEventsV1EventIdRegistrationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1EventIdRegistrations400JSONResponse Error

func (response PostEventsV1EventIdRegistrations400JSONResponse) VisitPostEventsV1EventIdRegistrationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1EventIdRegistrations403JSONResponse Error

func (response PostEventsV1EventIdRegistrations403JSONResponse) VisitPostEventsV1EventIdRegistrationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1EventIdRegistrations404JSONResponse Error

func (response PostEventsV1EventIdRegistrations404JSONResponse) VisitPostEventsV1EventIdRegistrationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1EventIdRegistrations409JSONResponse Error

func (response PostEventsV1EventIdRegistrations409JSONResponse) VisitPostEventsV1EventIdRegistrationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostEventsV1EventIdRegistrations500JSONResponse Error

func (response PostEventsV1EventIdRegistrations500JSONResponse) VisitPostEventsV1EventIdRegistrationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetEventsV1IdRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetEventsV1IdResponseObject interface {
	VisitGetEventsV1IdResponse(w http.ResponseWriter) error
}

type GetEventsV1Id200JSONResponse struct {
	Event Event `json:"event"`
}

func (response GetEventsV1Id200JSONResponse) VisitGetEventsV1IdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetEventsV1Id400JSONResponse Error

func (response GetEventsV1Id400JSONResponse) VisitGetEventsV1IdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetEventsV1Id404JSONResponse Error

func (response GetEventsV1Id404JSONResponse) VisitGetEventsV1IdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetEventsV1Id500JSONResponse Error

func (response GetEventsV1Id500JSONResponse) VisitGetEventsV1IdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PatchEventsV1IdRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *PatchEventsV1IdJSONRequestBody
}

type PatchEventsV1IdResponseObject interface {
	VisitPatchEventsV1IdResponse(w http.ResponseWriter) error
}

type PatchEventsV1Id200JSONResponse struct {
	Event Event `json:"event"`
}

func (response PatchEventsV1Id200JSONResponse) VisitPatchEventsV1IdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchEventsV1Id400JSONResponse Error

func (response PatchEventsV1Id400JSONResponse) VisitPatchEventsV1IdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PatchEventsV1Id404JSONResponse Error

func (response PatchEventsV1Id404JSONResponse) VisitPatchEventsV1IdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PatchEventsV1Id500JSONResponse Error

func (response PatchEventsV1Id500JSONResponse) VisitPatchEventsV1IdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get all events
	// (GET /events/v1)
	GetEventsV1(ctx context.Context, request GetEventsV1RequestObject) (GetEventsV1ResponseObject, error)
	// Create a new event
	// (POST /events/v1)
	PostEventsV1(ctx context.Context, request PostEventsV1RequestObject) (PostEventsV1ResponseObject, error)
	// Manually confirm a registration as paid
	// (POST /events/v1/admin/registrations/{eventId}/{email}/confirm)
	PostEventsV1AdminRegistrationsEventIdEmailConfirm(ctx context.Context, request PostEventsV1AdminRegistrationsEventIdEmailConfirmRequestObject) (PostEventsV1AdminRegistrationsEventIdEmailConfirmResponseObject, error)
	// Resend registration notifications
	// (POST /events/v1/admin/registrations/{eventId}/{email}/notify)
	PostEventsV1AdminRegistrationsEventIdEmailNotify(ctx context.Context, request PostEventsV1AdminRegistrationsEventIdEmailNotifyRequestObject) (PostEventsV1AdminRegistrationsEventIdEmailNotifyResponseObject, error)
	// Test email sending
	// (POST /events/v1/admin/test-email)
	PostEventsV1AdminTestEmail(ctx context.Context, request PostEventsV1AdminTestEmailRequestObject) (PostEventsV1AdminTestEmailResponseObject, error)
	// Test MailerLite integration
	// (POST /events/v1/admin/test-mailerlite)
	PostEventsV1AdminTestMailerlite(ctx context.Context, request PostEventsV1AdminTestMailerliteRequestObject) (PostEventsV1AdminTestMailerliteResponseObject, error)
	// Sign up for an event
	// (POST /events/v1/{eventId}/register)
	PostEventsV1EventIdRegister(ctx context.Context, request PostEventsV1EventIdRegisterRequestObject) (PostEventsV1EventIdRegisterResponseObject, error)
	// Get all registrations for an event
	// (GET /events/v1/{eventId}/registrations)
	GetEventsV1EventIdRegistrations(ctx context.Context, request GetEventsV1EventIdRegistrationsRequestObject) (GetEventsV1EventIdRegistrationsResponseObject, error)
	// Sign up for an event
	// (POST /events/v1/{eventId}/registrations)
	PostEventsV1EventIdRegistrations(ctx context.Context, request PostEventsV1EventIdRegistrationsRequestObject) (PostEventsV1EventIdRegistrationsResponseObject, error)
	// Get an event
	// (GET /events/v1/{id})
	GetEventsV1Id(ctx context.Context, request GetEventsV1IdRequestObject) (GetEventsV1IdResponseObject, error)
	// Update an event
	// (PATCH /events/v1/{id})
	PatchEventsV1Id(ctx context.Context, request PatchEventsV1IdRequestObject) (PatchEventsV1IdResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetEventsV1 operation middleware
func (sh *strictHandler) GetEventsV1(w http.ResponseWriter, r *http.Request, params GetEventsV1Params) {
	var request GetEventsV1RequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEventsV1(ctx, request.(GetEventsV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEventsV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEventsV1ResponseObject); ok {
		if err := validResponse.VisitGetEventsV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostEventsV1 operation middleware
func (sh *strictHandler) PostEventsV1(w http.ResponseWriter, r *http.Request) {
	var request PostEventsV1RequestObject

	var body PostEventsV1JSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostEventsV1(ctx, request.(PostEventsV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostEventsV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostEventsV1ResponseObject); ok {
		if err := validResponse.VisitPostEventsV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostEventsV1AdminRegistrationsEventIdEmailConfirm operation middleware
func (sh *strictHandler) PostEventsV1AdminRegistrationsEventIdEmailConfirm(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID, email openapi_types.Email) {
	var request PostEventsV1AdminRegistrationsEventIdEmailConfirmRequestObject

	request.EventId = eventId
	request.Email = email

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostEventsV1AdminRegistrationsEventIdEmailConfirm(ctx, request.(PostEventsV1AdminRegistrationsEventIdEmailConfirmRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostEventsV1AdminRegistrationsEventIdEmailConfirm")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostEventsV1AdminRegistrationsEventIdEmailConfirmResponseObject); ok {
		if err := validResponse.VisitPostEventsV1AdminRegistrationsEventIdEmailConfirmResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostEventsV1AdminRegistrationsEventIdEmailNotify operation middleware
func (sh *strictHandler) PostEventsV1AdminRegistrationsEventIdEmailNotify(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID, email openapi_types.Email) {
	var request PostEventsV1AdminRegistrationsEventIdEmailNotifyRequestObject

	request.EventId = eventId
	request.Email = email

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostEventsV1AdminRegistrationsEventIdEmailNotify(ctx, request.(PostEventsV1AdminRegistrationsEventIdEmailNotifyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostEventsV1AdminRegistrationsEventIdEmailNotify")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostEventsV1AdminRegistrationsEventIdEmailNotifyResponseObject); ok {
		if err := validResponse.VisitPostEventsV1AdminRegistrationsEventIdEmailNotifyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostEventsV1AdminTestEmail operation middleware
func (sh *strictHandler) PostEventsV1AdminTestEmail(w http.ResponseWriter, r *http.Request) {
	var request PostEventsV1AdminTestEmailRequestObject

	var body PostEventsV1AdminTestEmailJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostEventsV1AdminTestEmail(ctx, request.(PostEventsV1AdminTestEmailRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostEventsV1AdminTestEmail")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostEventsV1AdminTestEmailResponseObject); ok {
		if err := validResponse.VisitPostEventsV1AdminTestEmailResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostEventsV1AdminTestMailerlite operation middleware
func (sh *strictHandler) PostEventsV1AdminTestMailerlite(w http.ResponseWriter, r *http.Request) {
	var request PostEventsV1AdminTestMailerliteRequestObject

	var body PostEventsV1AdminTestMailerliteJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostEventsV1AdminTestMailerlite(ctx, request.(PostEventsV1AdminTestMailerliteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostEventsV1AdminTestMailerlite")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostEventsV1AdminTestMailerliteResponseObject); ok {
		if err := validResponse.VisitPostEventsV1AdminTestMailerliteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostEventsV1EventIdRegister operation middleware
func (sh *strictHandler) PostEventsV1EventIdRegister(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID, params PostEventsV1EventIdRegisterParams) {
	var request PostEventsV1EventIdRegisterRequestObject

	request.EventId = eventId
	request.Params = params

	var body PostEventsV1EventIdRegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostEventsV1EventIdRegister(ctx, request.(PostEventsV1EventIdRegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostEventsV1EventIdRegister")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostEventsV1EventIdRegisterResponseObject); ok {
		if err := validResponse.VisitPostEventsV1EventIdRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetEventsV1EventIdRegistrations operation middleware
func (sh *strictHandler) GetEventsV1EventIdRegistrations(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID, params GetEventsV1EventIdRegistrationsParams) {
	var request GetEventsV1EventIdRegistrationsRequestObject

	request.EventId = eventId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEventsV1EventIdRegistrations(ctx, request.(GetEventsV1EventIdRegistrationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEventsV1EventIdRegistrations")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEventsV1EventIdRegistrationsResponseObject); ok {
		if err := validResponse.VisitGetEventsV1EventIdRegistrationsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostEventsV1EventIdRegistrations operation middleware
func (sh *strictHandler) PostEventsV1EventIdRegistrations(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID, params PostEventsV1EventIdRegistrationsParams) {
	var request PostEventsV1EventIdRegistrationsRequestObject

	request.EventId = eventId
	request.Params = params

	var body PostEventsV1EventIdRegistrationsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostEventsV1EventIdRegistrations(ctx, request.(PostEventsV1EventIdRegistrationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostEventsV1EventIdRegistrations")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostEventsV1EventIdRegistrationsResponseObject); ok {
		if err := validResponse.VisitPostEventsV1EventIdRegistrationsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetEventsV1Id operation middleware
func (sh *strictHandler) GetEventsV1Id(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetEventsV1IdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEventsV1Id(ctx, request.(GetEventsV1IdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEventsV1Id")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEventsV1IdResponseObject); ok {
		if err := validResponse.VisitGetEventsV1IdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchEventsV1Id operation middleware
func (sh *strictHandler) PatchEventsV1Id(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request PatchEventsV1IdRequestObject

	request.Id = id

	var body PatchEventsV1IdJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchEventsV1Id(ctx, request.(PatchEventsV1IdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchEventsV1Id")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchEventsV1IdResponseObject); ok {
		if err := validResponse.VisitPatchEventsV1IdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xc+2/btvb/Vwh97w93gGLLeWythwJfx0m7bE0axEnXtSsGRjqy2UqkRlJ23ML/+8Uh",
	"JevpR9o07bIWF3exRPIcnueH59D+6PgiTgQHrpXT/+gofwIxNX8OgkCCMn8mUiQgNQPzyWd6jv8NQPmS",
	"JZoJ7vSdIdNzIiTRYsYd14EbGicROH1nwOfZs5jePAc+1hOnf+C5Tsx4/nHPdfQ8wdFKS8bHzsJ1fJFy",
	"LdsoZS/KRK5Gg7UEdlsIJEJpGg1FAE0a5+Yd8fFlmc5jb7fnVSntbt6K0lS3EBnhY5RZIsWUcb9Kanj7",
	"HSktAXQbIXxOaKbRMpXe7h45pYyTka5t6+Bgw74WriPh75RJCJz+m5y4a+0j33RFzIVS3y5XE9fvwNfI",
	"/bGUQraYW6ag/0gInb7zf93CYruZuXbNVENi4ToxKEXHZk7ZCknK4SYBX0NAAMcT4fuplBB0nE17y+wg",
	"X3kl97kxAU9jnHfCNUhOI/PScZ3nLGb6RapfhIci5QGq4oRPacSCYSqVGXIm9FN857jOcZzo+aEI5sWw",
	"7NMgkkCD+fENUxoXuYAxU1pS1PcwEgqC2sMrnlAWmHWSVL/EpczznLFBqif530OaaH9CM4rO24ZwXOd4",
	"Clw3VUWjSMwguAQaj9gHuKB8vFF1dtDCdYAHlyyuqW3X2z3Y8R7t9B5f7u72Pa/veR3P8147rhMKGVPt",
	"9J2AatjROLWFUxZUF/Syfzst/5f/Ky+epkZsKO4XPJo7fS1TaKMT0zGc0bjFzQckZBEQTmMgekI1AaM2",
	"wjjREyBXJ4QqBVoRLUiqgFBlnkdiLDoVX70WSgu+o0UqcTGuO++ScT1IeC3MRcKnlpn1uniej1u4Dqd1",
	"XZwMBwMyTBOCSrltsEAR1mx0jbZ/utzd6x887h88vp22yzReGPkbu2QaYrUxhqBNXzQWMBGF8RO7RG9J",
	"lEpJ54ZmGoE6Ev5zxt9XtzPROlH9bjcQvuqMhRhH0PFFjJ9TVF836NJAhSENFf4vCIPulMFsG40qNuZX",
	"CSaQjfsalYbaXCT1WkfrPerv/9g/2Ov0Hh1sL3p8/lrwFvtHYuSD4EBEaCwbUNIdcgQhTSNr91eXQ8JC",
	"woUmCnTV7AcxSObT7hnM/vpDyPdt1KcgVWbgy4m9lW7LuIYxyEaYN66eL5W5QMl7ysIr4tUqy263Rrc9",
	"SFY12ppfVphnIwgnkvkbo+6p4DCve8zlPNk48aI+vi7DxoJuxlHrpm4SkAy4D89hClE5dZ6JKTOIyOTQ",
	"GAJm4cQgmFLug8lLpdhUHdSwjxMesCkLUhqVN9AUHsSURVXPeEc5dAIB/589Qhcue4WdUvHZnrcZExon",
	"OLmn7ARLOW+MgjWNLFxnImIYZpi/Aetd0oDe2+z+vtJyQmuU7LgV866FiICakJ9EdA7yhIdik8TOi5FL",
	"fwIJwUB/XoTduLfPd927ipstPl8Lpbm11wTkLr1naWQV0VcsN9NmWxx5LvwVDk2LU+w62eSH3Vbgk5k6",
	"GYo4Tjmec4fANcjbmn1Nall6yTls25cN081NxXiMambaU8aFJMiiwlwb42zyX9aBDul5HnnyhPynh7Dz",
	"anT0QznF9jyvqWPXMacj7tcc/2p0VDZZpsTO/m7vp81nqHw1N+e/bcfnFb9bEZyru7aJkEbEvCehkASo",
	"PyHWjsr7zEzrjiN5yKTSZw2r+ZVyWHuC77Uhddq21JG47Uo12Rcslki0iX95ZKtKPqY3FY4s2mdxGpeJ",
	"l0wnZo2YspzgbYwnONvst53HWgYPGFpDzDjVtn4Q0yRBKfQ/OofzIvOv8v0V2MB1DucI0lZNw3eVCQs3",
	"l9rcqrAZFxeuIzi8CJ3+m/XxaAVPC3f9tCZPb2sCO6fzGENxq4P5EQOuR+BLW0VqwxFMgrKp7fZHsttk",
	"qGb8KDNXZqVGY5PJ5KkyB5oVE1kqvYIua0MaexxVT2NVofI0vhA249ngpqqu5K13DRcXQJaq03pbTROa",
	"Rq1ED7bwxyoEqGSunCO3bXdN0m0qaZhq0xppoinjx01Inr35JyPyfzGo3r4kU4XW66sw/yzcrYHGzTx/",
	"OQHylI0nmvExORV8LIQCdXtD+Oqofrm9CrCvOHRhDStxPVarwE8l0/MRytKGBeZTeghUgsSiNT65Np+e",
	"5sr89fdLx61hRFO7pL4PCstN74EjDMb5QrIPZodkAjQwcNHozViuWbcI+FjPM37mUzoU4j2DnINNxHwz",
	"GgWI75ef7FHDjP9rMBwej0Z/Xb747fisIEkT9hsWalAWLMvZteoyJ4PzE4N6Y8rpGE3H6EURygOCZSV8",
	"lCZmiH1jGh5MF1VdU1wiNfiztCKn1/E6ngEvCXCaMKfv7JlHqDo9MWrp2qW70x5+Gre1oS5ASwZTUISS",
	"iCmNZxQaRRlTjlneUsco7DwDbfhSL3uGkKQxaBM+3jRagqZ7guvNJiABK4qmVEdCKeJc7H+nIOeF1P28",
	"42L9tOqJf+w+Tl/v/ToJfjlVJ79E02B0GF/vvUxfDw89+uxq/Pr3px+CZy/nJ89e8tezJ0/aTj+N0xm9",
	"Ifbkg4xmOtKChKD9yQomIxYzXeExsFVTiwCqcIDe2IRegRQt8HzxFh1WJYIr61K7nueYThvXWV+HJknE",
	"7Jm6+07ZUFLwUMvTVpB3LD8XgzK9XfXeWSyXWSaGCVVncKPP6x3B9hxVC4GGheoaLWFq4TY6Prl55/62",
	"cJ39Wwp5Y7+zjfIhDQhuAJQ2RA/ug+gVf8+xPqJATkHa5mqnEr6d/pu3rqPSOKZybl277PlZM74luAUx",
	"4wR4kAjGNTqLL4FqIJRwmNnpjbiBvftS4MjEYTqndyYKa21NUZgXyOc1ZKwGTtmk0OoWn+l9n8TY5WTJ",
	"UNZ/+W6Tbz42Uvkbh6LJOW8Xrn1ZRhrFy4oxD5smiXSKhNg107plPKW6HzPwtOh+NOeVRdcXPGQyNgF2",
	"S2+IqXxPKCepae+TxB7ud8JIzEiZHPaUzYjZBGzXeaQlS4DM4HoixHsSUhZBQIQkPuWECxIJPgaJZizB",
	"ALWgQ0bAA9ubzli1axv2ieDEVJnydz/jRKCa+DSKFKESCAsgToQ2zb8zoVmY6dy+vQaldyAMhdR9Qsmu",
	"55HcTcg4pZJyDWDJV7bG7NZc0zw0/XUcYpmaUUUCiNgUsmseqyOFEW4ZAaljqyADV4eZbjbgkJOjSo8z",
	"T+oIkoqcXkbN5bjQjkQ+8RC3EY0cW62FTYH+N8PppXoq4nn1w4rtZHB+m81s20urc3+3gIXa2zPn2TG2",
	"FihlCoS1iAVtKZtpfekaQiGB6AlTxsgrXeuQRqr1DHxn9TBZRevlTW2DUS4LN4agstOvlxn2vf0vT7Qs",
	"VBMzQrxu9SAz0ynlKY2iea5oQluzwqelK44RfH6bbCVBAQ9WJRA8reIfjI93DHzGo2t2bKXW48osuQQ6",
	"406R0IRkY4ZdIEPD5rMOwXJHc64yWe4aiNkDg+Bnk25ioFzVsocyUOnTE8eZldL3vPEA8saXCd3bBOsq",
	"WpqBhMww/62Ret97fM/0mTIsYCx5kLniwgZnWZN5YXbtWUIb1J63aNozgT03UIJjqwRa0oAWJrKoBHwT",
	"mvNb6x1iE4rg0XyLgHwJSh+XIsynVAA2Xg3DDd02JFUjgR21LV7LEqUViClyosoywebi27beUFu+WCJP",
	"e0SlpoYdplE0/xqR5t7c7Kk9/eYCLcT5ZVytJGukl9tFu2/hMJAR07DawWwFYuliYynShDCOX+yIQD5n",
	"Ggy6okF2fB+zKWT+ZsyI6Q55KiQp97lde4nGsskUTkZnxK4CYctRRKXXyMk1yHwJbOy6hoytByxXwEc5",
	"RKAZDpTIL57+ESlkN3ZUh2DvyFYFaKrFzhg4OjsEpp6frZhICNkNfEpgOC1keqfRodpkf2NhC5X+pHHn",
	"6J2Y8AageesWte5NcWRDO9SYQPvXEfCpBWcTKNlL9T72n07Jdoy9PsNBfzrVq9nFG+ceGqX1iEVj+6WK",
	"PNzZw0CdKpqetcoa7xMgA6MbtTFMt7RCM4VvE7qPraPRenrFiSbfoRRnzIDjuy0VV23U6Ll+waG3u7d/",
	"8ONPjx63abBiRtupfbGFQEalxGKOeRBgg7IISCZImfX/HWnHWEAR6Ylp1ZUOD18mBZVcvE6wlIuKk3/e",
	"5K8mokSCT3VusfU9Hi3fY0IK6dS2aVHBWbXaGIDpT0di5pIZiyJbdo7F1M4yuSTVqYT18T07d1/kbD6c",
	"Q/cwEmkQRiZRppIrzSIgw8H55fCXQc738v5Cxrkf7izH7uRRZMt9vHr16lXn6Or09I+OuZDQwQerztd3",
	"316rHZ7XH8y+bLPtW6kAlPt3X71Ya2nufXmaZ0KT7PtStoBoPfv+ShC2n8tUUX4o82GT9n2VI0YiBsEN",
	"nsn7EEXuTHkA0vYispPLN9v8H+XxHgu7vL1jWk86WWV15dWi/EJBZXSVwprrRZXEkZN6QNnjrm9HGcx4",
	"+ytPVeU80JtPB/t7u73Pvs5U/2LBt3WrqaLI7xdJ7gqUbxHEVt6UGqFDq+XACqjeHjQ/wNj3HTl/E8iZ",
	"bfFN2lXfU2p8TR8ffg5oNrhtef7E5b7D6O8w+iHCaBYs1mJmFIQZTq7nxETUlSD5JLiTtMDuOSPcLeKD",
	"/IePtrmEW2v1madbt/rydP9w2/s2KHyrN7CayKyMwSgeXBoedZUE5iYwX+tT5zj5IXjVV7pXnxopf2nA",
	"cm+enm3nu8c/jENcLQY4i81U2pe36xqG28LCuRRB6uOHbFeO66QyKv3sGE1YB1ftzISMgq7TPBzhz6ZE",
	"JIBp2xL9bhd/+SqaCKX7e57ndfHXBP43AHIBSVwxVAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
